# Generated by Django 5.1.5 on 2025-02-03 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='comment',
            new_name='text',
        ),
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.FileField(upload_to='movies/'),
        ),
    ]
