# Generated by Django 5.1.5 on 2025-02-04 03:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_review_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchasedMovies', models.ManyToManyField(related_name='purchased_movies', to='movies.movie')),
                ('shoppingCart', models.ManyToManyField(related_name='shopping_cart', to='movies.movie')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('writtenReviews', models.ManyToManyField(to='movies.review')),
            ],
        ),
    ]
