# Generated by Django 5.1.5 on 2025-02-12 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_profile_purchasedmovies_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='movies',
        ),
        migrations.AddField(
            model_name='order',
            name='movies',
            field=models.JSONField(default=dict),
        ),
    ]
