# Generated by Django 5.1.5 on 2025-02-12 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_order_copies_remove_order_movies_order_movies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
